# Funding options for Montage AI
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: mfahsold
# ko_fi: montageai
# patreon: montageai
# custom: ["https://www.buymeacoffee.com/montageai"]
