apiVersion: batch/v1
kind: Job
metadata:
  name: manual-test-job
  namespace: montage-ai
spec:
  template:
    spec:
      containers:
      - name: worker
        image: <IMAGE_FULL>
        command: ["echo", "Manual test successful"]
      restartPolicy: Never
  backoffLimit: 1
